name = "vc-mdd-pv"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[vars]
# Add your environment variables here or in the dashboard
# META_PIXEL_ACCESS_TOKEN = "..."
# META_PIXEL_ID = "..."
# LOCATION_ENCRYPTION_KEY = "..."
# ADMIN_USERNAME = "..."
# ADMIN_PASSWORD = "..."
# GSHEET_GET_WH_URL = "..."
# GSHEET_POST_WH_URL = "..."
# TELEGRAM_BOT_URL = "..."
# N8N_LEAD_WEBHOOK_URL = "..."
